services:
  postgres:
    image: postgres:14.1-alpine
    container_name: muta_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=muta_dev
    ports:
      - '5433:5433'
    volumes:
      - db:/var/lib/postgresql/data
    command: -p 5433
volumes:
  db:
    driver: local
